#### Post Bad Req
POST http://localhost:3003/api/blogs
Content-Type: application/json; charset=utf-8

{
    "author": "fero2",
    "url": "https://test.fero.com",
    "likes": 100
}

#### Post Good Req
POST http://localhost:3003/api/blogs
Content-Type: application/json; charset=utf-8

{
    "title": "test2",
    "author": "fero2",
    "url": "https://test.fero.com",
    "likes": 1011,
    "userId":"692de3a4672fe46654226d90"
}

#### Delete Bad Req
DELETE http://localhost:3003/api/blogs/68e2aba83b97f1714d39baae

#### Delete Good Req (fill id in url everytime)
DELETE http://localhost:3003/api/blogs/68e2b3bd2b9f46a7d0dad2a1


#### GET Good Req
GET http://localhost:3003/api/blogs

#### GET Good Req Users
GET http://localhost:3003/api/users

#### POST Good Req Users - two times the user to have the uniqueness error
POST  http://localhost:3003/api/users
Content-Type: application/json; charset=utf-8

{
    "username": "federi",
    "name": "fero",
    "password": "FeroHash"
}

#### POST Wrong Req Users - Username Mandatory
POST  http://localhost:3003/api/users
Content-Type: application/json; charset=utf-8

{
    "name": "fero",
    "password": "FeroHash"
}

#### PUT Good Req
PUT http://localhost:3003/api/blogs/68e2abec3b97f1714d39bab2
Content-Type: application/json; charset=utf-8

{
    "likes": 499
}

#### PUT Bad Req
PUT http://localhost:3003/api/blogs/68e2ab68a1b6f2045a6bb7ed
Content-Type: application/json; charset=utf-8

{
    "likes": 500
}