GET http://localhost:3001/api/personas

#### GET Good Req
GET http://localhost:3001/api/personas/4

#### GET Bad Req
GET http://localhost:3001/api/personas/5

#### Delete Good Req
DELETE http://localhost:3001/api/personas/4

#### Delete Bad Req
DELETE http://localhost:3001/api/personas/5